version: '3.7'

services:
  web:
    build: ./django-app
    command: ./web.sh
    volumes:
      - ./django-app:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev.db
volumes:
  postgres_data: