# Generated by Django 4.1.4 on 2023-09-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0002_product_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visits_count", models.IntegerField()),
            ],
        ),
    ]
