# Generated by Django 4.1.4 on 2023-06-01 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Meal')),
                ('dishes', models.ManyToManyField(to='diets.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('brand', models.CharField(max_length=256, verbose_name='Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammage', models.IntegerField(verbose_name='Grammage')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.meal', verbose_name='Meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('meals', models.ManyToManyField(to='diets.meal', verbose_name='Meals')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammage', models.IntegerField(verbose_name='Grammage')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.dish', verbose_name='Dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.product', verbose_name='Product')),
            ],
        ),
    ]
